#!/usr/bin/env python3
from pprint import pprint
from tokenizer import Tokenizer
from parser import Parser
from type_check import type_check

SRC = """
if (1) {
  xxx = 27;
  y = 5;
} else if (2)
  y = true;
else while (5) y = 2;
"""
SRC2 = """
x = 0xAB8 + -y * a >> 7 || 2;


x = a ^ b == c;
x = a == b ^ c;

x = a >> b == c;
x = a == b >> c;

x = (a + b) == c;
x = a == (b + c);
x = a >> b == c;
x = a == b >> c;
x = a || b + c;
"""
SRC3 = """
+ - / * % ^ & | = == != >= <= << >> || &&
"""
SRC = """

x = a + b * (c >> 2);

"""

tokenizer = Tokenizer(SRC)
tokenizer.tokenize()

# print(tokenizer.lnum)
# pprint(tokenizer.tokens)

parser = Parser(tokenizer.tokens)
ast = parser.parse()
pprint(ast)

ast = type_check(ast)
